### ISSUE TITLE
Getting TypeError: Failed to fetch

### ISSUE THREAD

**Issue by dragonfire1119** [mpociot/laravel-testtools#11]
When I installed the extension I'm getting a error in the console.

```
Uncaught (in promise) TypeError: Failed to fetch
    at TypeError (native)
```

Chrome Version 49.0.2623.112 m
Extension Version: 0.2.0

The Version before 0.2.0 which was 0.1.2 works.

I also tested this extension on a brand new install of vivaldi 1.0 & same problem.

**Comment by mpociot** [comment]
Thanks for reporting!

This error seems to happen in combination with uglify js - that's why I didn't notice it during development, as I only use `grunt watch` without the file compression (because if faster processing).

I added `charset="utf-8"` to the .html files and now it's working with the packed version.

Version 0.2.1 is tagged and uploaded to the chrome web store. It might take 60 minutes until you see an update.
